version: 2

jobs:
   centos_build:
      docker:
         # - image: hill119/esgf_centos6
         - image: muryanto1/mycentos:latest
      working_directory: workspace
      steps:
         - run: git clone https://github.com/ESGF/esgf-installer.git
         - run: cd esgf-installer; git checkout python_devel
         - run: wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda2.sh
         - run: bash ./miniconda2.sh -b -p miniconda2

workflows:
   version: 2
   esgf_installer:
      jobs:
         - centos_build
