version: 2

aliases:
   - &create_esgf_pub_env
     name: create_esgf_pub_env
     command: |
        pwd
        ls -l        

jobs:
   centos_build:
      docker:
         # - image: hill119/esgf_centos6
         - image: muryanto1/mycentos:latest
      working_directory: workspace
      steps:
         - checkout
         - run: *create_esgf_pub_env        

workflows:
   version: 2
   esgf_installer:
      jobs:
         - centos_build
