version: 2

jobs:
   centos_build:
      docker:
         # - image: hill119/esgf_centos6
         - image: muryanto1/mycentos:latest
      working_directory: workspace
      steps:
         - checkout
         - run: "pwd"
         - run: "ls -l"

workflows:
   version: 2
   esgf_installer:
      jobs:
         - centos_build
